name: notify-issue

on:
  issues:
    types: [opened]

jobs:
  issue:
    runs-on: ubuntu-latest
    name: New Issue Notification
    steps:
      - run: |
          echo "{\"text\":\"GoVultr : New Issue https://github.com/vultr/govultr/issues/${{ github.event.number }} \"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: ${{ secrets.MATTERMOST_USERNAME}}
          MATTERMOST_ICON: ${{ secrets.MATTERMOST_ICON }}
